/**
 * v1.2.0 Phase 5.4 -- reference implementation for the 13th lifecycle hook.
 *
 * Subscribes to `lifecycle.session.reflection` and writes a reflection
 * artifact at `<nexusHome>/reflections/<sessionId>.md` containing:
 *
 *   - The session id and timestamp.
 *   - A scan of the transcript for "user said X, I did Y wrong" patterns.
 *   - The list of files written during the session.
 *
 * The artifact is intentionally drafted for human review -- it does not
 * mutate AGENTS.md or any skill file directly. A subsequent
 * `/wrap-up-session` invocation surfaces the artifact alongside the
 * other end-of-session paperwork.
 *
 * The hook is wired by the daemon at session-construction time; the
 * subscription is disposed when the daemon shuts down.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { nexusHome } from "../storage/paths.js";
import type { Disposable } from "../telemetry/TelemetryBus.js";
import type {
  HookBus,
  LifecycleSessionReflectionEvent,
} from "./HookBus.js";

/**
 * Pattern set used to mine the transcript for reflection-worthy spans.
 * Each entry is a regex on the message body; matches are surfaced
 * verbatim in the artifact so the user can see exactly which spans the
 * hook picked up.
 */
export interface ReflectionPattern {
  readonly id: string;
  readonly description: string;
  readonly pattern: RegExp;
}

export const DEFAULT_REFLECTION_PATTERNS: readonly ReflectionPattern[] = [
  {
    id: "user-corrected",
    description: "User explicitly corrected the agent.",
    pattern:
      /\b(no(?:t)? (?:that|like that)|don't|do not|stop doing|wrong|incorrect|that's not (?:what|right))\b/i,
  },
  {
    id: "user-confirmed",
    description: "User confirmed a non-obvious approach worked.",
    pattern: /\b(yes,?\s+(?:exactly|right|that's it)|perfect|good call)\b/i,
  },
  {
    id: "user-said-i-did-wrong",
    description: "Explicit 'user said X, I did Y wrong' pattern.",
    pattern: /(?:you|i)\s+(?:said|asked)[\s\S]{1,80}?(?:wrong|incorrect|miss)/i,
  },
];

export interface ReflectionArtifact {
  readonly sessionId: string;
  readonly isoTime: string;
  readonly findings: ReadonlyArray<{
    readonly patternId: string;
    readonly description: string;
    readonly excerpt: string;
  }>;
  readonly filesWritten: readonly string[];
}

export interface SessionReflectionOptions {
  /** Override the nexus-home dir (test injection). */
  readonly homeDir?: string;
  /** Override the pattern set (test injection). */
  readonly patterns?: readonly ReflectionPattern[];
  /** Override the file writer (test injection). */
  readonly writeFile?: (filePath: string, content: string) => void;
  /** Override the directory creator (test injection). */
  readonly mkdir?: (dirPath: string) => void;
}

/**
 * Build the reflection artifact from a session-end event. Pure function;
 * does no I/O. Useful in tests and when the hook subscriber wants to
 * inspect the artifact before writing.
 */
export function buildReflectionArtifact(
  event: LifecycleSessionReflectionEvent,
  patterns: readonly ReflectionPattern[] = DEFAULT_REFLECTION_PATTERNS,
): ReflectionArtifact {
  const findings: Array<{
    patternId: string;
    description: string;
    excerpt: string;
  }> = [];
  const transcript = event.transcript ?? "";
  // Walk paragraph-style chunks so the excerpt is human-meaningful.
  const chunks = transcript.split(/\n{2,}|^---$/m).map((s) => s.trim()).filter(Boolean);
  for (const pattern of patterns) {
    for (const chunk of chunks) {
      if (pattern.pattern.test(chunk)) {
        findings.push({
          patternId: pattern.id,
          description: pattern.description,
          excerpt: chunk.length > 280 ? chunk.slice(0, 280) + "..." : chunk,
        });
      }
    }
  }
  return {
    sessionId: event.sessionId,
    isoTime: event.isoTime,
    findings,
    filesWritten: event.filesWritten ?? [],
  };
}

/** Render the artifact as a Markdown blob ready to write to disk. */
export function renderReflectionMarkdown(artifact: ReflectionArtifact): string {
  const lines: string[] = [];
  lines.push(`# Session reflection -- ${artifact.sessionId}`);
  lines.push("");
  lines.push(`**Generated**: ${artifact.isoTime}`);
  lines.push("");
  lines.push(`Auto-generated by the v1.2.0 Phase 5.4 reflection hook. Drafted for human review; nothing here has been applied.`);
  lines.push("");

  lines.push(`## Files written (${artifact.filesWritten.length})`);
  lines.push("");
  if (artifact.filesWritten.length === 0) {
    lines.push("_(none)_");
  } else {
    for (const p of artifact.filesWritten) {
      lines.push(`- \`${p}\``);
    }
  }
  lines.push("");

  lines.push(`## Reflection findings (${artifact.findings.length})`);
  lines.push("");
  if (artifact.findings.length === 0) {
    lines.push("_No reflection-worthy spans detected by the default patterns._");
  } else {
    for (const f of artifact.findings) {
      lines.push(`### ${f.patternId} -- ${f.description}`);
      lines.push("");
      lines.push("```");
      lines.push(f.excerpt);
      lines.push("```");
      lines.push("");
    }
  }
  return lines.join("\n");
}

/**
 * Subscribe the reflection hook to a `HookBus`. Returns a `Disposable`
 * that unsubscribes on dispose. The hook writes the artifact under
 * `<nexusHome>/reflections/<sessionId>.md` when the event fires.
 */
export function attachSessionReflectionHook(
  bus: HookBus,
  opts: SessionReflectionOptions = {},
): Disposable {
  const home = opts.homeDir ?? nexusHome();
  const patterns = opts.patterns ?? DEFAULT_REFLECTION_PATTERNS;
  const writeFile = opts.writeFile ?? ((p, c) => fs.writeFileSync(p, c, "utf-8"));
  const mkdir = opts.mkdir ?? ((d) => fs.mkdirSync(d, { recursive: true }));

  return bus.on("lifecycle.session.reflection", (event) => {
    try {
      const artifact = buildReflectionArtifact(event, patterns);
      const dir = path.join(home, "reflections");
      mkdir(dir);
      const file = path.join(dir, `${event.sessionId}.md`);
      writeFile(file, renderReflectionMarkdown(artifact));
    } catch {
      // Reflection failures are non-fatal -- the hook MUST NOT take down
      // the daemon's session-end path.
    }
  });
}
