#!/usr/bin/env node
/**
 * Regenerate docs/index.md as a per-module summary catalog.
 *
 * Quick-orientation document for new contributors and AI agents: one row per
 * top-level src/ subdirectory listing file count, total LOC, the entry-point
 * hint, and the top exported symbols. Output is byte-deterministic with
 * respect to src/ contents; rerunning the script with no source changes
 * produces no diff.
 *
 * Inputs: src/<subdir>/**.ts
 * Output: docs/index.md
 *
 * Hand-written one-liners live in MODULE_DESCRIPTIONS below. CI runs
 * `npm run catalog:check` (regenerate then `git diff --exit-code`) so
 * out-of-sync rows fail the build.
 *
 * Run via: `npm run catalog`.
 */

import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const SRC_DIR = join(REPO_ROOT, "src");
const OUTPUT_PATH = join(REPO_ROOT, "docs", "index.md");

/**
 * Hand-written one-line summaries. Keep these short and keep them honest:
 * if the module's purpose drifts, update the line. Adding a new top-level
 * module to src/ requires adding a row here.
 */
const MODULE_DESCRIPTIONS = {
  agents:
    "Sub-agent orchestration: SubAgentManager spawns scoped verification, research, and planning sub-agents; SpecialistLoader resolves prompts via the workspace -> bundled -> hardcoded priority chain (ADR-0004).",
  chat:
    "Conversation, prompt assembly, streaming, and the six-stage compaction pipeline (ADR-0003). PromptBuilder owns budget allocation; ContextCompactor owns the strategy chain.",
  commands:
    "Slash command router for in-extension commands like /memory, /verify, /research, /commit, /review-pr.",
  config:
    "Settings reader (vscode.workspace.getConfiguration) and prompt-budget allocator. Single source of truth for percentage-based budget splits across system prompt, memory, skills, conversation, and reserve.",
  desktop:
    "Desktop-shell discovery and proxy bridge: daemonDiscovery decides between proxy / extension-only / opt-in modes when the VS Code extension boots. Wires the legacy extension surface to the v1.0.0 Tauri shell + Node sidecar over JSON-RPC.",
  evaluation:
    "Golden-task suite plus the YAML cross-check generated by scripts/generate-golden-tasks.mjs. Smoke set runs in-process; harness corpus runs out-of-process.",
  guardrails:
    "Pre-execution safety layer: ActionClassifier, GitSafetyNet (checkpoints + protected-branch refusal), LoopDetector, BudgetEnforcer, PermissionTiers (ADR-0005).",
  llm:
    "Vendor-neutral LLM port at types.ts; the Ollama HTTP adapter at OllamaClient/OllamaHttp. The only module allowed to import the concrete Ollama clients (modulo grandfathered baselines).",
  mcp:
    "Model Context Protocol client (consume external servers) and server (expose Gemma's tools to other clients). Lifecycle managed by McpManager.",
  observability:
    "Tracer + TraceStore for structured spans; MetricsCollector for counters; OtlpExporter for optional OTLP HTTP fan-out (off by default for offline-first).",
  orchestration:
    "Orchestrator + PlannerAgent + DAGExecutor + ReflexionEngine for multi-step plan execution. Composes sub-agents from src/agents/.",
  panels:
    "VS Code webview panels and message protocol. Communication with the runtime goes through panels/messages.ts; direct storage imports are forbidden.",
  runtime:
    "NexusCodingRuntime composition root. Wires Tracer, settings, and the dependency graph that the panel and command layers consume.",
  skills:
    "User-defined skill loader. Reads SKILL.md files from ~/.nexus/skills/ and contributes them as system-prompt augmentations.",
  storage:
    "Four-layer memory (Working, Episodic, Semantic, Graph) plus ChatHistoryStore, ToolOutputCache, and the consolidator. UnifiedMemoryRetriever is the public retrieval API (ADR-0002).",
  tools:
    "Tool registry, agent loop, output redirector, and the handlers under tools/handlers/. Routes every call through ConfirmationGate and PermissionTiers.",
  utils:
    "Logger, error formatting (formatForUser/formatForLog), Markdown renderer (DOMPurify-sanitized), and small shared helpers.",
};

/** Recursively collect all .ts files under a directory. */
function collectTypeScriptFiles(dir) {
  const out = [];
  const entries = readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...collectTypeScriptFiles(full));
    } else if (entry.isFile() && entry.name.endsWith(".ts")) {
      out.push(full);
    }
  }
  return out;
}

/** Count lines in a file. Accepts CRLF or LF without distinction. */
function lineCount(filePath) {
  const text = readFileSync(filePath, "utf-8");
  return text.split(/\r?\n/).length;
}

/**
 * Extract exported top-level names from a TypeScript file. Conservative:
 * we only match `export (default? )?(class|type|interface|function|const) Name`
 * patterns. Re-exports (`export { Foo }`) are not counted because they
 * duplicate exports from elsewhere; the goal is to point readers at the
 * symbols defined here.
 */
function extractExports(filePath) {
  const text = readFileSync(filePath, "utf-8");
  const out = [];
  const re = /^export\s+(?:default\s+)?(?:abstract\s+)?(class|type|interface|function|const|enum)\s+(\w+)/gm;
  let m;
  while ((m = re.exec(text)) !== null) {
    out.push({ kind: m[1], name: m[2] });
  }
  return out;
}

/**
 * Pick the entry-point file for a module: prefer the file whose basename
 * matches the directory's PascalCase form (e.g. agents/SubAgentManager.ts),
 * otherwise fall back to the largest file by LOC. Tie-break alphabetically.
 */
function pickEntryPoint(moduleName, files) {
  const pascal = moduleName.charAt(0).toUpperCase() + moduleName.slice(1);
  const candidates = [
    `${pascal}.ts`,
    `${pascal}Manager.ts`,
    `${moduleName}.ts`,
    "index.ts",
  ];
  for (const cand of candidates) {
    const hit = files.find((f) => f.endsWith(`/${cand}`) || f.endsWith(`\\${cand}`));
    if (hit) return hit;
  }
  // Fallback: largest LOC, tie-break alphabetical.
  const ranked = files
    .map((f) => ({ f, loc: lineCount(f) }))
    .sort((a, b) => b.loc - a.loc || a.f.localeCompare(b.f));
  return ranked[0]?.f ?? files[0];
}

/** Aggregate stats per top-level module. */
function summarizeModule(moduleName, modulePath) {
  const files = collectTypeScriptFiles(modulePath).sort();
  const loc = files.reduce((acc, f) => acc + lineCount(f), 0);
  const allExports = files.flatMap(extractExports);
  // Top exports: most-occurring names across files (cheap proxy for "central"
  // symbols). Stable sort by count desc, then alphabetical.
  const counts = new Map();
  for (const exp of allExports) {
    counts.set(exp.name, (counts.get(exp.name) ?? 0) + 1);
  }
  const top = [...counts.entries()]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .slice(0, 3)
    .map(([name]) => name);
  const entryPoint = pickEntryPoint(moduleName, files);
  const entryRel = entryPoint.replace(REPO_ROOT, "").replace(/\\/g, "/").replace(/^\//, "");
  return {
    name: moduleName,
    fileCount: files.length,
    loc,
    entryPoint: entryRel,
    topExports: top,
  };
}

function renderMarkdown(modules) {
  const lines = [];
  lines.push("# Gemma Code Module Catalog");
  lines.push("");
  lines.push(
    "Per-module summary of `src/`. This file is regenerated by `npm run catalog` (driven by [scripts/generate-catalog.mjs](../scripts/generate-catalog.mjs)) and verified in CI; do not hand-edit. The hand-written one-liners live in `MODULE_DESCRIPTIONS` inside the script.",
  );
  lines.push("");
  lines.push(
    "For the ADR-level architecture see [../ARCHITECTURE.md](../ARCHITECTURE.md) and [../docs/adr/](adr/). For the boundary rules CI gates on, see [../configs/dependency-cruiser.cjs](../configs/dependency-cruiser.cjs).",
  );
  lines.push("");
  lines.push("## Modules");
  lines.push("");
  lines.push("| Module | Files | LOC | Entry point | Top exports |");
  lines.push("|--------|------:|----:|-------------|-------------|");
  for (const m of modules) {
    const entry = m.entryPoint
      ? `[${m.entryPoint}](../${m.entryPoint})`
      : "(none)";
    const exports = m.topExports.length > 0 ? m.topExports.map((n) => "`" + n + "`").join(", ") : "(none)";
    lines.push(
      `| \`${m.name}\` | ${m.fileCount} | ${m.loc} | ${entry} | ${exports} |`,
    );
  }
  lines.push("");
  lines.push("## Module purposes");
  lines.push("");
  for (const m of modules) {
    const desc = MODULE_DESCRIPTIONS[m.name];
    if (!desc) {
      lines.push(`### \`${m.name}\``);
      lines.push("");
      lines.push(
        "_(missing one-liner; add an entry to `MODULE_DESCRIPTIONS` in [scripts/generate-catalog.mjs](../scripts/generate-catalog.mjs).)_",
      );
      lines.push("");
      continue;
    }
    lines.push(`### \`${m.name}\``);
    lines.push("");
    lines.push(desc);
    lines.push("");
  }
  lines.push("---");
  lines.push("");
  lines.push(
    "_Generated by [scripts/generate-catalog.mjs](../scripts/generate-catalog.mjs). Last regenerated time is recorded in `git log -1 -- docs/index.md`; the file content itself is byte-deterministic with respect to `src/` so a no-op regeneration produces no diff._",
  );
  lines.push("");
  return lines.join("\n");
}

function main() {
  const subdirs = readdirSync(SRC_DIR, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort((a, b) => a.localeCompare(b));

  const modules = subdirs.map((name) => summarizeModule(name, join(SRC_DIR, name)));
  // Deterministic output: regeneration with no src/ change produces no diff.
  const md = renderMarkdown(modules);
  writeFileSync(OUTPUT_PATH, md, "utf-8");
  const moduleCount = modules.length;
  // Single-line summary; suppress noisy progress unless DEBUG is set.
  process.stdout.write(`docs/index.md regenerated: ${moduleCount} modules\n`);
}

main();
